<template>
    <naive-config>
      <n-message-provider>
        <NuxtLayout>
          <v-app>
            <NuxtPage/>
          </v-app>
        </NuxtLayout>
      </n-message-provider>
    </naive-config>
</template>
